In [60]:
import pandas as pd
import numpy as np

year_used = "2016"
columns = ["State",year_used]

In [61]:
#Political Factor DataFrame (based on Popular Vote in 2016 Presidental Election)
election2016_file = "Resources/2016/data/election2016.csv"
election2016_data =  pd.read_csv(election2016_file)
election2016_data = pd.DataFrame(election2016_data)
gov_election2016_data = election2016_data.copy()
gov_election2016_data = gov_election2016_data.iloc[:56,:4] 
convert_to_number_list = ["Democratic Candidates","Republican Candidates","Other Candidates"]
for item in ["Democratic Candidates","Republican Candidates","Other Candidates"]:
    for x in range(len(gov_election2016_data[item])):
        gov_election2016_data[item][x] = int(gov_election2016_data[item][x].replace(',' , ''))
    
us_states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}
gov_election2016_data["Party"] = gov_election2016_data["State"]
for state in range(len(gov_election2016_data["State"])):
    try:
        if gov_election2016_data.iloc[state,1] > gov_election2016_data.iloc[state,2]:
            if gov_election2016_data.iloc[state,1] > gov_election2016_data.iloc[state,3]:
                gov_election2016_data.iloc[state, 4] = "D"
        elif gov_election2016_data.iloc[state,2] > gov_election2016_data.iloc[state,1]:
            if gov_election2016_data.iloc[state,2] > gov_election2016_data.iloc[state,3]:
                gov_election2016_data.iloc[state, 4] = "R"
        else:
            gov_election2016_data.iloc[state, 4] = "I"
        gov_election2016_data["State"][state] = us_states[gov_election2016_data["State"][state]]
    except:
        None
gov_election2016_data = gov_election2016_data[["State","Party"]]
gov_election2016_data.to_csv("output/gov_election2016.csv", index=False, header=True)
gov_election2016_data

                       State Party
0                    Alabama     R
1                     Alaska     R
2             American Samoa     R
3                    Arizona     R
4                   Arkansas     R
5                 California     D
6                   Colorado     D
7                Connecticut     D
8                   Delaware     D
9       District of Columbia     D
10                   Florida     R
11                   Georgia     R
12                      Guam     D
13                    Hawaii     D
14                     Idaho     R
15                  Illinois     D
16                   Indiana     R
17                      Iowa     R
18                    Kansas     R
19                  Kentucky     R
20                 Louisiana     R
21                     Maine     D
22                  Maryland     D
23             Massachusetts     D
24                  Michigan     R
25                 Minnesota     D
26               Mississippi     R
27                  Missouri     R
28                   Montana     R
29                  Nebraska     R
30                    Nevada     D
31             New Hampshire     D
32                New Jersey     D
33                New Mexico     D
34                  New York     D
35            North Carolina     R
36              North Dakota     R
37  Northern Mariana Islands     I
38                      Ohio     R
39                  Oklahoma     R
40                    Oregon     D
41              Pennsylvania     R
42               Puerto Rico     I
43              Rhode Island     D
44            South Carolina     R
45              South Dakota     R
46                 Tennessee     R
47                     Texas     R
48                      Utah     R
49                   Vermont     D
50            Virgin Islands     D
51                  Virginia     D
52                Washington     D
53             West Virginia     R
54                 Wisconsin     R
55                   Wyoming     R

In [62]:
#Population Data Cleanup to DataFrame
file = "Resources/ALL/data/population2010-2019.csv"
total_population_data_file_all = pd.read_csv(file)
total_population_data_file = total_population_data_file_all.copy()
total_population_data_file = total_population_data_file.iloc[5:,4:17]
total_population_data_file = total_population_data_file.reset_index()
total_population_data_file = total_population_data_file.iloc[:,1:]
total_population_data_file = total_population_data_file.rename(columns={"NAME":"State"})
total_population_data_file = total_population_data_file.rename(columns={f"POPESTIMATE{year_used}":f"{year_used}"})
total_population_data_file = total_population_data_file.loc[:,columns]
total_population_data_file = total_population_data_file.iloc[:51]
total_population_data_file.dtypes
total_population_data_file = pd.merge(total_population_data_file,gov_election2016_data, on="State")
total_population_data_file

                   State      2016 Party
0                Alabama   4863525     R
1                 Alaska    741456     R
2                Arizona   6941072     R
3               Arkansas   2989918     R
4             California  39167117     D
5               Colorado   5539215     D
6            Connecticut   3578141     D
7               Delaware    948921     D
8   District of Columbia    685815     D
9                Florida  20613477     R
10               Georgia  10301890     R
11                Hawaii   1427559     D
12                 Idaho   1682380     R
13              Illinois  12820527     D
14               Indiana   6634304     R
15                  Iowa   3131371     R
16                Kansas   2910844     R
17              Kentucky   4438182     R
18             Louisiana   4678135     R
19                 Maine   1331317     D
20              Maryland   6003323     D
21         Massachusetts   6823608     D
22              Michigan   9950571     R
23             Minnesota   5522744     D
24           Mississippi   2987938     R
25              Missouri   6087135     R
26               Montana   1040859     R
27              Nebraska   1905616     R
28                Nevada   2917563     D
29         New Hampshire   1342307     D
30            New Jersey   8870827     D
31            New Mexico   2091630     D
32              New York  19633428     D
33        North Carolina  10154788     R
34          North Dakota    754434     R
35                  Ohio  11634370     R
36              Oklahoma   3926331     R
37                Oregon   4089976     D
38          Pennsylvania  12782275     R
39          Rhode Island   1056770     D
40        South Carolina   4957968     R
41          South Dakota    862996     R
42             Tennessee   6646010     R
43                 Texas  27914410     R
44                  Utah   3041868     R
45               Vermont    623657     D
46              Virginia   8410106     D
47            Washington   7294771     D
48         West Virginia   1831023     R
49             Wisconsin   5772628     R
50               Wyoming    584215     R

In [64]:
#Veteran Population Data Cleanup to DataFrame
veteran_file = f"Resources/{year_used}/data/veteran_{year_used}.csv"
veteran_data = pd.read_csv(veteran_file)
veteran_data_file = veteran_data.copy()
#S2101_C01_001E Population Data
#S2101_C03_001E Veteran Data
data_columns = ["NAME","S2101_C01_001E","S2101_C03_001E"]
veteran_data_file = veteran_data_file[data_columns]
veteran_data_file = veteran_data_file.iloc[1:,:]
for column in data_columns:
    try:
        veteran_data_file[column] = veteran_data_file[column].astype(np.float64)
    except ValueError:
        None
veteran_data_file[year_used] = veteran_data_file[data_columns[2]]/veteran_data_file[data_columns[1]]
veteran_data_file = veteran_data_file.rename(columns={"NAME":"State"})
veteran_data_file = veteran_data_file[columns]
veteran_data_file = pd.merge(veteran_data_file,gov_election2016_data, on="State")
total_population_data_file

                   State      2016 Party
0                Alabama   4863525     R
1                 Alaska    741456     R
2                Arizona   6941072     R
3               Arkansas   2989918     R
4             California  39167117     D
5               Colorado   5539215     D
6            Connecticut   3578141     D
7               Delaware    948921     D
8   District of Columbia    685815     D
9                Florida  20613477     R
10               Georgia  10301890     R
11                Hawaii   1427559     D
12                 Idaho   1682380     R
13              Illinois  12820527     D
14               Indiana   6634304     R
15                  Iowa   3131371     R
16                Kansas   2910844     R
17              Kentucky   4438182     R
18             Louisiana   4678135     R
19                 Maine   1331317     D
20              Maryland   6003323     D
21         Massachusetts   6823608     D
22              Michigan   9950571     R
23             Minnesota   5522744     D
24           Mississippi   2987938     R
25              Missouri   6087135     R
26               Montana   1040859     R
27              Nebraska   1905616     R
28                Nevada   2917563     D
29         New Hampshire   1342307     D
30            New Jersey   8870827     D
31            New Mexico   2091630     D
32              New York  19633428     D
33        North Carolina  10154788     R
34          North Dakota    754434     R
35                  Ohio  11634370     R
36              Oklahoma   3926331     R
37                Oregon   4089976     D
38          Pennsylvania  12782275     R
39          Rhode Island   1056770     D
40        South Carolina   4957968     R
41          South Dakota    862996     R
42             Tennessee   6646010     R
43                 Texas  27914410     R
44                  Utah   3041868     R
45               Vermont    623657     D
46              Virginia   8410106     D
47            Washington   7294771     D
48         West Virginia   1831023     R
49             Wisconsin   5772628     R
50               Wyoming    584215     R